import { lazy } from "react";
import { pageElement } from "./routeSupport";
const Dashboard = lazy(() => import("@/Components/Dashboard/Dashboard"));
const Send = lazy(() => import("@/Components/Account/Send"));
const History = lazy(() => import("@/Components/Account/History"));
const Security = lazy(() => import("@/Components/Account/Security"));
const Cards = lazy(() => import("@/Components/Cards/Cards"));
const Inbox = lazy(() => import("@/Components/Inbox/Inbox"));
const Profile = lazy(() => import("@/Components/Profile/Profile"));
const KycUpgrade = lazy(() => import("@/Components/Kyc/KycUpgrade"));
const Statements = lazy(() => import("@/Components/Statements/Statements"));
const AgentCash = lazy(() => import("@/Components/Agent/AgentCash"));
const Signups = lazy(() => import("@/Components/Agent/Signups"));
const AssistedSignup = lazy(() => import("@/Components/Agent/AssistedSignup"));
const MyAgents = lazy(() => import("@/Components/Agent/MyAgents"));
const Stores = lazy(() => import("@/Components/Stores/Stores"));
const MobileMoney = lazy(() => import("@/Components/Account/MobileMoney"));
const Terminals = lazy(() => import("@/Components/Terminals/Terminals"));
export const dashboardRoutes = [
  { path: "dashboard", element: pageElement(Dashboard) },
  { path: "send", element: pageElement(Send) },
  { path: "history", element: pageElement(History) },
  { path: "cards", element: pageElement(Cards) },
  { path: "statements", element: pageElement(Statements) },
  { path: "notifications", element: pageElement(Inbox) },
  { path: "profile", element: pageElement(Profile) },
  { path: "verification", element: pageElement(KycUpgrade) },
  { path: "security", element: pageElement(Security) },
  { path: "agent", element: pageElement(AgentCash) },
  { path: "signups", element: pageElement(Signups) },
  { path: "signups/new", element: pageElement(AssistedSignup) },
  { path: "my-agents", element: pageElement(MyAgents) },
  { path: "stores", element: pageElement(Stores) },
  { path: "mobile-money", element: pageElement(MobileMoney) },
  { path: "terminals", element: pageElement(Terminals) },
];
